image:
  tag: latest

service:
  type: NodePort
  edgeService:
    type: NodePort
    nodePort: 30066

startServices: "s3,sqs,sns,dynamodb,lambda,iam,sts,cloudwatch,logs,ec2,apigatewayv2,secretsmanager,cognito-identity,cognito-idp,events"

enableStartupScripts: false

debug: true

extraEnvVars:
  - name: LOCALSTACK_AUTH_TOKEN
    value: "ls-VeHAXOqU-YoLu-2004-TOvI-zuhiqaDOffef"
  - name: DEBUG
    value: "1"
  - name: DOCKER_HOST
    value: "unix:///var/run/docker.sock"

volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket

volumeMounts:
  - name: docker-sock
    mountPath: /var/run/docker.sock